01-05-2025 11:09:42 | INFO     | __main__:27 | Using GPU: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
01-05-2025 11:09:42 | INFO     | __main__:32 | TensorFlow Version: 2.17.0
01-05-2025 11:09:42 | INFO     | __main__:33 | Is CUDA enabled: False
01-05-2025 11:09:42 | INFO     | __main__:34 | Is ROCm enabled: True
01-05-2025 11:09:45 | INFO     | __main__:53 | Starting WebSocket server...
01-05-2025 11:09:45 | INFO     | websockets.server:341 | server listening on 192.168.1.5:8765
01-05-2025 11:10:25 | INFO     | websockets.server:529 | connection open
01-05-2025 11:10:25 | INFO     | handlers.connection:155 | New connection
01-05-2025 11:10:39 | INFO     | handlers.auth_handler:83 | User 'yoavon2' authenticated with ID 680d405ca183764e786f0ef9.
01-05-2025 11:10:39 | INFO     | handlers.contacts_handler:101 | Retrieved 3 contacts for user '680d405ca183764e786f0ef9'
01-05-2025 11:10:39 | INFO     | handlers.contacts_handler:101 | Retrieved 3 contacts for user '680d405ca183764e786f0ef9'
01-05-2025 11:10:39 | INFO     | handlers.call_handler:175 | Set model preference for 680d405ca183764e786f0ef9 to lip
01-05-2025 11:10:39 | INFO     | handlers.call_handler:175 | Set model preference for 680d405ca183764e786f0ef9 to lip
01-05-2025 11:10:58 | INFO     | handlers.call_handler:43 | Call invite from 680d405ca183764e786f0ef9 to 67d6bae7386c75bcc71b6890
01-05-2025 11:11:02 | INFO     | handlers.call_history_handler:79 | Fetched 6 history entries for user 680d405ca183764e786f0ef9
01-05-2025 11:11:07 | INFO     | handlers.call_history_handler:79 | Fetched 6 history entries for user 680d405ca183764e786f0ef9
01-05-2025 11:11:09 | INFO     | handlers.call_history_handler:79 | Fetched 6 history entries for user 680d405ca183764e786f0ef9
01-05-2025 11:11:11 | INFO     | handlers.call_handler:175 | Set model preference for 680d405ca183764e786f0ef9 to vosk
01-05-2025 11:11:12 | INFO     | handlers.call_handler:175 | Set model preference for 680d405ca183764e786f0ef9 to lip
01-05-2025 11:11:22 | ERROR    | handlers.connection:193 | Connection loop error
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 988, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yoav/VSCode/Lip-C/server/handlers/connection.py", line 170, in handle_connection
    async for raw in ws:
  File "/home/yoav/VSCode/Lip-C/server/venv/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 242, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "/home/yoav/VSCode/Lip-C/server/venv/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 322, in recv
    raise self.protocol.close_exc from self.recv_exc
websockets.exceptions.ConnectionClosedError: no close frame received or sent
01-05-2025 11:11:26 | INFO     | websockets.server:440 | server closing
01-05-2025 11:11:26 | INFO     | websockets.server:473 | server closed
01-05-2025 11:13:01 | INFO     | __main__:27 | Using GPU: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
01-05-2025 11:13:01 | INFO     | __main__:32 | TensorFlow Version: 2.17.0
01-05-2025 11:13:01 | INFO     | __main__:33 | Is CUDA enabled: False
01-05-2025 11:13:01 | INFO     | __main__:34 | Is ROCm enabled: True
01-05-2025 11:13:03 | INFO     | __main__:53 | Starting WebSocket server...
01-05-2025 11:13:03 | INFO     | websockets.server:341 | server listening on 192.168.1.5:8765
01-05-2025 11:13:05 | INFO     | websockets.server:440 | server closing
01-05-2025 11:13:05 | INFO     | websockets.server:473 | server closed
